const express = require('express')
const cors = require('cors')
const cookie = require('cookie-parser')
const DatabaseConnect = require('./configs/db')
const AuthRouter = require('./routers/Auth/auth.router')
const AdminRouter = require('./routers/Education/admin.router')
const CheckAdmin = require('./middlewares/checkAdmin')
const TeacherRouter = require('./routers/Education/teacher.router')
const StudentRouter = require('./routers/Education/student.router')
require('dotenv').config()
const app = express()
app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use(cors(({ origin: 'https://education-management-git-master-jeel-narolas-projects.vercel.app'})))
app.use(cookie())
app.use('/Auth',AuthRouter)
app.use('/Admin',CheckAdmin,AdminRouter)
app.use('/Teacher',CheckAdmin,TeacherRouter)
app.use('/Student',CheckAdmin,StudentRouter)
app.get("/",(req,res)=>{
    res.json({message:"Welcome To Eduction Management Application."})
})

app.listen(process.env.PORT,()=>{
    console.log("server Start :- ",process.env.PORT)
    DatabaseConnect()
})